name: Sync

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:yahinstudio/StaticServerForPages.git
          destination-repo: git@gitee.com:yahinstudio/StaticServerForPages.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: yahinstudio
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: yahinstudio/StaticServerForPages
          branch: main